/*
What numbers could be generated by randomGenerator.nextDouble() * 3
+ 1; where randomGenerator is an object of type Random?
 */

/*
0.0 included to 4.0 excluded
 */

package chapter3.Section5_Random;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.Random;

public class Ex_3_45_Random_generator {

    public static void main(String[] args) {
        Random randomGenerator = new Random();
        double randomNumber = randomGenerator.nextDouble() * 3 + 1;
        System.out.println(randomNumber);
        System.out.printf("%.2f%n", randomNumber);

        DecimalFormat pattern0dot00 = new DecimalFormat("0.00");
        System.out.println(pattern0dot00.format(randomNumber));

        NumberFormat moneyFormatter = NumberFormat.getCurrencyInstance(Locale.GERMANY);
        System.out.println(moneyFormatter.format(randomNumber));
    }
}
