/*
What numbers could be generated by randomGenerator.nextInt(5) + 10;
where randomGenerator is an object of type Random?
 */

/*
generate 10-14
 */

package chapter3.Section5_Random;

import java.util.Random;

public class Ex_3_44_Random_generator {

    public static void main(String[] args){
        Random randomGenerator = new Random();
        int number = randomGenerator.nextInt(5) + 10;  // generate 0-4 + 10:  10-14
        System.out.println(number);
        assert(number >= 10 && number <= 14);
    }
}
