package chapter1.Section1_Intro;

public class Ex_1_6_Object_program {
    /*
    What is an object program?
     */
    // An object program is the machine code that is generated by a compiler.
    // Formally:
    // The translated program that is produced by a compiler is called the object program
    // or object code.
}
